services:
  - type: web
    name: creatorsuite
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: APP_URL
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: B2_ENDPOINT
        sync: false
      - key: B2_REGION
        sync: false
      - key: B2_BUCKET_NAME
        sync: false
      - key: B2_KEY_ID
        sync: false
      - key: B2_APP_KEY
        sync: false
      - key: B2_PUBLIC_BASE_URL
        sync: false
      - key: MONGODB_URI
        sync: false
